name: sm_image
description: "A Flutter package that provides a widget to load images from the
  web with caching support."
version: 0.0.3
homepage: "https://github.com/shay-wong/flutter_sm_image"
repository: "https://github.com/shay-wong/flutter_sm_image"
issue_tracker: "https://github.com/shay-wong/flutter_sm_image/issues"

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  loading_animation_widget: ^1.2.1
  octo_image: ^2.0.0
  sm_logger: ^0.0.7

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/src/generated/
  line_length: 120
  assets:
    outputs:
      package_parameter_enabled: true
