name: flutter_sm_image
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_sm_logger:
    git:
      url: https://github.com/shay-wong/flutter_sm_logger.git
      ref: main
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
